version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/uploads:/app/uploads
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: .
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=user_info
      - REDIS_HOST=redis
      - MONGO_HOST=mongo
    depends_on:
      - mysql
      - redis
      - mongo
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user_info
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: mysqld --default_authentication_plugin=mysql_native_password
    networks:
      - app-network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - app-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  mongo_data: 